services:
  - type: web
    name: online-school
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python seed.py && python bot.py & gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: online-school-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: false
      - key: BOT_TOKEN
        sync: false

databases:
  - name: online-school-db
    region: frankfurt
    plan: free
    databaseName: online_school
    ipAllowList: []
